# -*- coding: utf-8 -*-
"""Jathin_Boston_Housing_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cK9ktuNzmumKL7pbcrFO2ExF53i_yYOj

# 🏠 Predicting Boston House Prices using Machine Learning

👋 Welcome! This is **Jathin**, and here is the notebook I've built for predicting Boston house pricing using a simple machine learning approach.

In this project, we’ll walk through the steps of:
- Understanding and preparing the dataset
- Training a Linear Regression model
- Evaluating how well it performs
- Visualizing predictions to interpret the results

Let’s dive in!
"""

# 📦 Step 1: Import Libraries
# These libraries help us with data manipulation, visualization, and machine learning modeling.

import pandas as pd  # for handling datasets
import numpy as np   # for numerical operations
import matplotlib.pyplot as plt  # for visual plots
import seaborn as sns  # for heatmaps and visuals

# scikit-learn for preprocessing, modeling and evaluation
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.impute import SimpleImputer

"""## 📥 Step 2: Upload and View the Dataset

Let’s upload the CSV dataset manually and inspect the first few rows.

"""

# Upload the dataset file (HousingData.csv)
from google.colab import files
uploaded = files.upload()

# Read the uploaded file into a Pandas DataFrame
import io
df = pd.read_csv(io.BytesIO(uploaded['HousingData.csv']))

# Display the first 5 records
df.head()

"""## 🔍 Step 3: Exploratory Data Analysis (EDA)

Now let’s explore the dataset to understand the variables and find potential patterns or issues.

"""

# Check dataset structure and column data types
df.info()

# Generate descriptive statistics for all numeric columns
df.describe()

# Check for missing values
print("\nMissing Values in Dataset:")
print(df.isnull().sum())

# Create a heatmap showing correlation between variables
plt.figure(figsize=(12, 8))
sns.heatmap(df.corr(numeric_only=True), annot=True, fmt=".2f", cmap='coolwarm')
plt.title("Correlation Heatmap of Boston Housing Features")
plt.show()

"""## 🧹 Step 4: Data Cleaning and Preprocessing

We’ll handle missing values and split the dataset into training and test sets for our machine learning model.

"""

# Separate features (X) from the target column 'MEDV' (Median value of owner-occupied homes)
X = df.drop("MEDV", axis=1)
y = df["MEDV"]

# Use mean imputation to fill in any missing values
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

# Split into 80% training and 20% testing data
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.2, random_state=42)

"""## 🤖 Step 5: Model Building with Linear Regression

Let’s train a simple Linear Regression model using the prepared data.

"""

# Initialize and train the Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict target values on the test set
y_pred = model.predict(X_test)

# Show a comparison of actual vs predicted values
comparison = pd.DataFrame({'Actual Price': y_test.values, 'Predicted Price': y_pred})
comparison.head()

"""## 📊 Step 6: Model Evaluation and Visualization

Let’s evaluate how well our model performs using standard metrics like Mean Squared Error and R² score.

"""

# Evaluate model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"✅ Mean Squared Error (MSE): {mse:.2f}")
print(f"✅ R² Score: {r2:.2f}")

# Visual plot: Predicted vs Actual
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, alpha=0.7)
plt.xlabel("Actual MEDV (House Price)")
plt.ylabel("Predicted MEDV")
plt.title("Predicted vs Actual House Prices")
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color="red", linestyle="--")
plt.grid(True)
plt.show()